language: node_js
node_js:
  - 7
install:
  - npm install
script:
  - npm build
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
deploy:
  provider: firebase
  token: "$FIREBASE_TOKEN"